### PR TITLE
Add a BlendModeShaders demo

### PR DESCRIPTION
**Pull request by xerosugar**
some shader effects

### CODE REVIEW

**Comment by Gama11** [comment]
@xerosugar The color swap shader doesn't work for me:

```
Shader.hx:244: Could not compile the shader:
        Fragment shader failed to compile with the following errors:
ERROR: 0:49: error(#164) l-value required: assign "colorOld" (can't modify a uniform)
ERROR: 0:50: error(#164) l-value required: assign "colorOld" (can't modify a uniform)
ERROR: 0:51: error(#164) l-value required: assign "colorOld" (can't modify a uniform)
ERROR: 0:53: error(#164) l-value required: assign "colorNew" (can't modify a uniform)
ERROR: 0:54: error(#164) l-value required: assign "colorNew" (can't modify a uniform)
ERROR: 0:55: error(#164) l-value required: assign "colorNew" (can't modify a uniform)
ERROR: error(#273) 6 compilation errors.  No code generated
```

**Comment by Gama11** [comment]
Ok, I think I found a solution for it. :)

**Comment by Gama11** [comment]
Thanks, this is quite a cool demo!

As you can see, I did a (quite) bit of code cleanup before merging. This is what the demo looks like now:

reaha0e

**Comment by xerosugar** [comment]
Wow! You spent the whole day on this cleanup, thank **you** :D As I think I said a looong while ago, these are the kind of effects that I think a 2D-game framework should provide for its users and now it's finally available to everyone to use, awesome! :+1:

**Pull request merged**
