### PR TITLE
Updated FlxBlur demo to no longer be Flash-only

### PR DESCRIPTION
**Pull request by p-brighenti**
Changed this demo's implementation to no longer be Flash only as the previous implementation produced no effect when it ran on non-flash targets. Pressing the `space` key while running the previous implementation on a, let's say, HTML 5 build had no visible changes on the game screen.

Do let me know if you need me to change anything in this PR, like having a camera specifically for the effect in addition to the main camera.

If this PR gets approved, will it be enough to update the demo on the website as well (after a new build)? Or will I need to open another PR in the website's repo for that?

### CODE REVIEW

**Comment by Geokureli** [comment]
> If this PR gets approved, will it be enough to update the demo on the website as well (after a new build)? Or will I need to open another PR in the website's repo for that?

You'll need to update this file, too: https://github.com/HaxeFlixel/haxeflixel.com/blob/master/src/documents/demos/FlxBlur.html.md
here's an example:
https://github.com/HaxeFlixel/haxeflixel.com/blob/dev/src/documents/demos/BSPMapGen.html.md

**Comment by Geokureli** [comment]
Got a chance to try this change, you forgot to import `openfl.filters.BlurFilter` so this doesn't compile, and if that is the filter you meant to use, it's not the same filter effect as the flash version

new Html5 version:
Screen Shot 2021-09-13 at 9 26 22 PM


Old Flash version:
Screen Shot 2021-09-13 at 9 29 21 PM

We already have demos showcasing the gaussian blur filter, and [FlxTrailArea](https://haxeflixel.com/demos/FlxTrailArea/). I see no reason to update this as it's showcasing some old flash specific feature we had

**Comment by Gama11** [comment]
Agree with @Geokureli, doesn't really sense to update it to a much different-looking effect.

**Comment by p-brighenti** [comment]
Ah my bad, I didn't know it was a different effect. I'm guessing I accidentally removed the import while cleaning up the code.
Thanks for the review.

**Pull request closed without merging**
