### PR TITLE
Update for the gamepad API refactor (HaxeFlixel/flixel#1502)

### PR DESCRIPTION
**Pull request by larsiusprime**
Updates the GamepadTest demo to work with the new gamepad input in my flixel PR:

https://github.com/HaxeFlixel/flixel/pull/1502

### CODE REVIEW

**Comment by larsiusprime** [comment]
I should note this also updates the cursor demo as well. That requires this Flixel-UI PR:

https://github.com/HaxeFlixel/flixel-ui/pull/103

**Comment by Gama11** [comment]
There's at least one more demo that uses gamepads (Mode).

**Comment by larsiusprime** [comment]
Cool, thanks for the heads up.

**Comment by larsiusprime** [comment]
Oh, this is perfect, wonderful demonstration of how the new API simplifies so much.

**Comment by larsiusprime** [comment]
@Gama11: new changes to mode are up. Any other demos that use gamepads?

**Comment by Gama11** [comment]
Doesn't look like it. Should be much simpler to add gamepad input to more demos from now on though! :)

**Comment by larsiusprime** [comment]
Okay I think I'm finished now @gama11

**Pull request merged**
