### PR TITLE
Update Slime.hx

### PR DESCRIPTION
**Pull request by Funlamb**
I believe this is missing the proper return signature. Please accept this request if it is. If it isn't please let me know why because I have been looking at this code for about an hour now trying to figure out the FSM.

### CODE REVIEW

**Comment by Gama11** [comment]
It's not really _missing_ it per se, Haxe has type inference, which makes explicit return types optional.

https://haxe.org/manual/type-system-type-inference.html

Flixel's code style still generally adds the return type explicitly though.

Were you having any issues without this?

Btw, pull requests go to the dev branch.

**Comment by Funlamb** [comment]
I wasn't having an issue with the code. It was just something I saw as I was trying to figure out how the states are being switched in this demo. 

Where is the line of code that is changing the state of the FSM? I'm not seeing it. 

I'll put pull requests on the dev branch next time. This is the first time I've have ever found anything in code that looked off.

**Comment by Gama11** [comment]
There's no line like that, it happens implicitly. The FSM checks the available transitions which are defined here: https://github.com/HaxeFlixel/flixel-demos/blob/2.3.0/Features/FlxFSM/source/Slime.hx#L34-L40

For instance, there's a transition defined to go from the `Idle` to the `Jump` state. The transition is made when the condition is met / when `Conditions.jump()` returns `true`.

**Comment by Funlamb** [comment]
Thanks. I had been looking at that code for hours trying to figure that out.

**Pull request merged**
