### PR TITLE
TiledEditor: add a flipped image

### PR DESCRIPTION
**Pull request by Tembac**
As mentioned in the PR for Addons I added the flipping to the demo so we can test it. It is crashing under Neko and windows.

https://github.com/HaxeFlixel/flixel-addons/pull/288#pullrequestreview-20460187

issue: https://github.com/HaxeFlixel/flixel-addons/issues/287

### CODE REVIEW

**Comment by Gama11** [comment]
Thanks, I can clearly observe the difference now. :)

**Comment by Gama11** [comment]
I wanted to decrease the image size a bit before merging, but looks like I don't have permissions - I guess you didn't enable this checkbox? https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png

**Comment by Tembac** [comment]
I have it checked. http://puu.sh/tSTq3/acdf8d42f3.png

I you still can't let me know which size do you want and I can resize it.

**Comment by Gama11** [comment]
Still doesn't work.. odd. Might be an issue on GitHub's end, been having weird issues with commits being delayed and whatnot.

I'll just merge and make a separate commit to dev instead.

**Pull request merged**
