### PR TITLE
bigger FlxLightPuzzle

### PR DESCRIPTION
**Pull request by ninjamuffin99**
doubles the window / game size of FlxLightPuzzle
The lower quality assets upscaled annoyed me, so internally i also updated all the numbers to work with a bigger screen resolution / game size.

Addresses the `- [ ] FlxLightPuzzle` part of 
> increase window size of small demos, we can double the window size and keep the FlxGame to the same dimesnions

from #287 

One last thing in this demo is if someone wants to make bigger graphics for
- Music pause/unpause Icon
- Retry Icon

and find 
- higher res haxeflixel logo

### CODE REVIEW

**Comment by Geokureli** [comment]
1024px may be too big for the html5 demo for most monitors, no?

**Comment by ninjamuffin99** [comment]
1024 i believe is the WIDTH, where 1920 is usually the standard size for
fullscreen width. 1080 is HEIGHT

**Comment by Geokureli** [comment]
i may have my numbers mixed up, my macbook can display 1024 easily, I'll check my mini win machine tomorrow

**Comment by ninjamuffin99** [comment]
follow up on dis georgie 🤔

**Comment by Geokureli** [comment]
ugh, fine. later today

**Comment by Geokureli** [comment]
Thanks!

**Pull request merged**
