### PR TITLE
Flappybalt + Sound and Music

### PR DESCRIPTION
**Pull request by PlayStateWolf**
Some of the sound and music code might need some revising

### CODE REVIEW

**Comment by Gama11** [comment]
The entire files are marked as changed. Did you accidentally change the line endings or something?

**Comment by PlayStateWolf** [comment]
I'm not positively sure why my uploaded files come up as completely
overwritten, if this causes some confusion I'd be perfectly okay
downloading the Flappybalt folder structure onto my computer from the main
repo and only apply edits where necessary. I do assure you though that the
overall project and it's files remain practically the same except for my
added sounds and music files and their code.

Please let me know how we should move forward with this

**Comment by Gama11** [comment]
I fixed the whitespace changes, but it seems like the ogg files might be broken as well? Not hearing anything in-game or when playing them in VLC.

**Comment by PlayStateWolf** [comment]
I can hear the file just fine in VLC media player, perhaps it didn't push
to the repo properly, I'll try again soon

**Comment by Gama11** [comment]
Closing since there hasn't been any followup.

**Pull request closed without merging**
