### PR TITLE
Added example of Unicode Combining Diacritical Marks to FlxBitmapText Demo

### PR DESCRIPTION
**Pull request by SeiferTim**
Added new angle code format bitmap font and xml.
Changed size of demo window
Added new `FlxBitmapText` that shows off combining characters.

See also https://github.com/HaxeFlixel/flixel/pull/2309.

### CODE REVIEW

**Comment by SeiferTim** [comment]
image

**Comment by Gama11** [comment]
Nice!

I expect that font is fine to use, copyright-wise?

**Comment by SeiferTim** [comment]
Uh-oh I hadn't really considered that... I just made the image using one of the basic windows fonts...
How can I tell and/or where can I find some for-sure 'free' to use fonts if that is a problem?

**Comment by Gama11** [comment]
Not sure where to find them, I thought you're the bitmap font expert. :D Something with a permissive creative commons license should be safe to use for instance, I think.

**Comment by SeiferTim** [comment]
So, I learned something new:

Windows says:

> **If I convert the font into a bitmap font can I include that in my game or app?**
> 
> No, converting Windows fonts to other formats does not change the rules around embedding or redistribution, and format conversion itself is not allowed. Many Microsoft supplied fonts are available for app and game licensing through the original font foundry or Monotype.

Whereas:

> Google Fonts allows commercial use of their huge font library so is the logical first place to look for any website or online project. All of the fonts use the Open Fonts License which grants unrestricted rights to use, modify, share or whatever.

...so I'll re-make this font with a Google Font and re-commit...

**Pull request merged**
