### PR TITLE
FlxInvaders sounds and music

### PR DESCRIPTION
**Pull request by ninjamuffin99**
adds sound effects and music to FlxInvaders

the music is an old track I made, so license / rights is all clear lol!

the sounds are .wav as I've seen other demos use that, and the music is .ogg which works on everything except flash and iOS Safari (i believe). If we make browser mobile versions of all the demos we should make sure we dont forget to check in on that

### CODE REVIEW

**Comment by Geokureli** [comment]
I mention [here](https://github.com/HaxeFlixel/flixel-demos/issues/287), I want to completely redo this demo at some point because it's such a not fun rendition

that has nothing to do with this PR i just wanted to vent

**Comment by Geokureli** [comment]
@ninjamuffin99 Looks like this broke CI on flash targets
>  source/PlayerShip.hx:68: characters 15-20 : flixel.sound.FlxSound has no field pitch
> source/PlayState.hx:216: characters 13-18 : flixel.sound.FlxSound has no field pitch

**Comment by ninjamuffin99** [comment]
hmmm... instead of wrapping the demo in `FLX_PITCH`, do you think on the flixel side we can just document that setting `pitch` won't do anything on flash targets? I think people using flixel for flash purposes are likely low nowadays!

Along with that, did we want to still even build / compile flash demos? 

Otherwise, I can wrap it in `FLX_PITCH` 🤝

**Comment by Geokureli** [comment]
Im not against the convenience of adding a do-nothing pitch to flash, but i still think the demo should still check FLX_PITCH, since it's the easier fix and it can teach people about how to use the FLX_PITCH flag

**Pull request merged**
