### PR TITLE
Added Shaders to the Wiggle Effects.

### PR DESCRIPTION
**Pull request by REALHaydenGaming**
Yes I know, I stole a bunch of code from the Flixel Blend Modes Shaders thing. But I'ma list them down:

- Added a prettier look to the BG in the battle HUD (yeah, super unsatisfied with how the FlxWaveMode did it.)
- **Wiggle Effects.** (Customize this with 5 different Wiggle Shaders.)

### CODE REVIEW

**Comment by Geokureli** [comment]
can you show a before and after video comparing the new and old effect

**Comment by Geokureli** [comment]
Getting the error:
> source/CombatHUD.hx:18: characters 8-36 : Type not found : openfl8.effects.WiggleEffect

Does this require a new haxelib?

**Comment by REALHaydenGaming** [comment]
> Getting the error:
> 
> > source/CombatHUD.hx:18: characters 8-36 : Type not found : openfl8.effects.WiggleEffect
> 
> Does this require a new haxelib?

**This code was taken from the Blend Mode Shaders, I'll showcase a screenshot of the old one with the new one.**

**Comment by Geokureli** [comment]
be sure to test your changes locally and fix any errors before creating PRs.

The classes you're referring to in BlendmodeShaders are here:
https://github.com/HaxeFlixel/flixel-demos/blob/dev/Effects/BlendModeShaders/source/openfl8/effects/WiggleEffect.hx
https://github.com/HaxeFlixel/flixel-demos/blob/dev/Effects/BlendModeShaders/source/openfl3/effects/WiggleEffect.hx

I'm gonna close this, even if the new effects look better I don't want the main HaxeFlixel tutorial to say "now copy these 2 giant files to specific new folders of your project, also we're not going to teach you what they do" it's much easier to just use a premade effect, and let them try out other effects if they are curious

**Pull request closed without merging**
